exclamacion_positiva <- c("¡Eso!",
                          "¡Qué padre!",
                          "¡Bien!",
                          "¡Simón!",
                          "¡Chingón!",
                          "¡A huevo!",
                          "¡A wiwi!",
                          "¡Chido!",
                          "¡Cámara!",
                          "¡Súper!",
                          "¡Chilo!",
                          "¡Ándale!",
                          "¡Ah chingá!",
                          "¡Asústame pantera!")
