exclamacion_positiva <- c("¡Eso!",
                          "¡Qué padre!",
                          "¡Bien!",
                          "¡Simón!",
                          "¡Chingón!",
                          "¡A huevo!",
                          "¡Chido!",
                          "¡Cámara!",
                          "¡Súper!",
                          "¡Chilo!")
