frase_positiva <-  c("Ya la hiciste.",
                      "Ya estás del otro lado.",
                      "Te la pelan.",
                      "Sigue así.",
                      "Eres unx buenazx.",
                      "Programas bien perrón.",
                      "Estás con tokio.",
                      "Salu2 Kli2.",
                      "Puedes eso y más.",
                      "Te lo van a aceptar en CRAN.")
