tradicionales_positivas <- c("A cada capillita le llega su fiestecita.",
                             "Abuelita soy tu nieto.",
                             "Te hace lo que el viento a Juárez.",
                             "El que nace pa tamal del cielo le caen las hojas.",
                             "¡Asústame pantera!",
                             "Ya vas llegando a Pénjamo.",
                             "¡Estás bien Quacker mi avena!",
                             "¡El que es perico donde quiera es verde!",
                             "¡Ya rugiste, Lión!",
                             "¡Ya estufas mi jardín!")
